# Generated by Django 5.2.8 on 2025-11-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
